---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: grafana
  namespace: flux-system
  labels:
    app.kubernetes.io/part-of: observability-stack
spec:
  interval: 1h
  url: https://grafana.github.io/helm-charts
  timeout: 3m

