---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: local-ron-mallory-infrastructure
  namespace: flux-system

# Base configuration from parent local cluster
resources:
  - ../../../infrastructure

# KIND-specific patches
patchesJson6902:
  - path: metric-server-patch.yaml
    target:
      kind: Deployment
      name: metrics-server
      namespace: kube-system

