---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: grafana
  namespace: flux-system
spec:
  interval: 10m
  path: ./platform/components/grafana/releases/11.3.0/
  prune: true
  wait: true
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: loki
    - name: tempo
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: grafana
      namespace: observability

