---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: local-infrastructure
  namespace: flux-system

resources:
  - cert-manager.yaml       # Base dependency
  - opentelemetry.yaml     # Depends on cert-manager
  # - cnpg.yaml              # Independent component
  # - kyverno.yaml           # Independent component
  # - sealed-secrets.yaml    # Independent component
  - metric-server.yaml     # Independent component
  - cluster-scoped-grafana.yaml  # Independent component
