---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: local-infrastructure
  namespace: flux-system

resources:
  # Flux Kustomizations with proper dependency management
  - cert-manager.yaml       # Base dependency
  - cnpg.yaml              # Independent component
  - kyverno.yaml           # Independent component
  - sealed-secrets.yaml    # Independent component
  - opentelemetry.yaml     # Depends on cert-manager
  - metric-server.yaml     # Independent component
  # Observability Stack (OTel-centric)
  - loki.yaml              # Log aggregation - depends on cert-manager
  - tempo.yaml             # Distributed tracing - depends on cert-manager
  # - grafana.yaml           # Visualization - depends on loki, tempo
  - otel-collector.yaml    # Telemetry collection - depends on opentelemetry, loki, tempo
