---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metric-server
  namespace: flux-system
spec:
  interval: 10m
  path: ./platform/components/metric-server/releases/0.8.0/components/
  prune: true
  wait: true
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: metrics-server
      namespace: kube-system
