---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: opentelemetry
  namespace: flux-system
spec:
  interval: 10m
  path: ./platform/components/open-telemetry/releases/0.135.0/
  prune: true
  wait: true
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: cert-manager
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: opentelemetry-operator-controller-manager
      namespace: opentelemetry-operator-system
