---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: otel-collector
  namespace: flux-system
spec:
  interval: 10m
  path: ./platform/components/otel-collector/releases/0.97.0/
  prune: true
  wait: true
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: opentelemetry
    - name: loki
    - name: tempo
  healthChecks:
    - apiVersion: opentelemetry.io/v1beta1
      kind: OpenTelemetryCollector
      name: otel-collector-gateway
      namespace: observability
    - apiVersion: opentelemetry.io/v1beta1
      kind: OpenTelemetryCollector
      name: otel-collector-agent
      namespace: observability

