---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
  namespace: flux-system
  labels:
    app.kubernetes.io/name: loki
    app.kubernetes.io/part-of: observability-stack
spec:
  interval: 5m
  timeout: 10m
  chart:
    spec:
      chart: loki
      version: 6.16.0
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  targetNamespace: observability
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    deploymentMode: SingleBinary

    loki:
      auth_enabled: false
      server:
        http_listen_port: 3100
        grpc_listen_port: 9096
        grpc_server_max_recv_msg_size: 8388608
        grpc_server_max_send_msg_size: 8388608

      common:
        replication_factor: 1

      storage:
        type: filesystem
        filesystem:
          chunks_directory: /var/loki/chunks
          rules_directory: /var/loki/rules

      schemaConfig:
        configs:
          - from: 2024-04-01
            store: tsdb
            object_store: filesystem
            schema: v13
            index:
              prefix: loki_index_
              period: 24h

      limits_config:
        reject_old_samples: true
        reject_old_samples_max_age: 168h
        ingestion_rate_mb: 16
        ingestion_burst_size_mb: 32
        max_query_series: 100000

      compactor:
        retention_enabled: true
        retention_delete_delay: 2h
        retention_delete_worker_count: 150

      analytics:
        reporting_enabled: false

      tracing:
        enabled: true

    singleBinary:
      replicas: 1
      resources:
        limits:
          cpu: 1000m
          memory: 2Gi
        requests:
          cpu: 100m
          memory: 128Mi

      extraEnv:
        - name: JAEGER_AGENT_HOST
          value: tempo.observability.svc.cluster.local
        - name: JAEGER_AGENT_PORT
          value: "14268"
        - name: JAEGER_SAMPLER_TYPE
          value: "ratelimiting"
        - name: JAEGER_SAMPLER_PARAM
          value: "1.0"

      persistence:
        enabled: true
        size: 10Gi
        storageClass: ""
        accessModes:
          - ReadWriteOnce

    # ServiceMonitor for Prometheus monitoring
    monitoring:
      serviceMonitor:
        enabled: true
        interval: 15s
        scrapeTimeout: 10s
        namespace: observability
        labels: {}

    # Test configuration
    test:
      enabled: false

    # Gateway configuration (disabled for single binary mode)
    gateway:
      enabled: false

    # Disable distributed components for single binary mode
    ingester:
      replicas: 0
    distributor:
      replicas: 0
    querier:
      replicas: 0
    queryFrontend:
      replicas: 0
    queryScheduler:
      replicas: 0
    compactor:
      replicas: 0
    indexGateway:
      replicas: 0
    bloomCompactor:
      replicas: 0
    bloomGateway:
      replicas: 0
